<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "aw_resize"
 *
 * Auto generated by Extension Builder 2013-12-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Image Resizer',
	'description' => 'resize images on-demand in the backend',
	'category' => 'module',
	'author' => 'alex',
	'author_email' => 'websurfer992@gmail.com',
	'author_company' => 'alex-web.gr',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.3.0',
	'constraints' => array(
        'depends' => array(
            'typo3' => '6.1.2-6.1.3',
            'extbase' => '6.0',
            'fluid' => '6.0',
        ),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);


?>
